<?php
declare(strict_types=1);

class SomeClass
{
    public static $publicStaticProperty1;

    public static $publicStaticProperty2;

    public $publicProperty1;

    public $publicProperty2;
    
    protected static $protectedStaticProperty1;

    protected static $protectedStaticProperty2;

    protected $protectedProperty1;

    protected $protectedProperty2;
    
    private $privateProperty1;

    private $privateProperty2;
}

?>
